### ISSUE TITLE
Status update and PyPI

### ISSUE THREAD

**Issue by marcan** [andre-d/pympv#8]
What's the status of this project? I see it hasn't had any updates in years. I'm interested in using it myself and seeing it added to PyPI, but I'd like to know if you intend to continue maintaining it or if I should just maintain my own fork and submit it to PyPI myself. Let me know what you prefer :-)

I created a PR with the changes in my repo: https://github.com/andre-d/pympv/pull/7

**Comment by andre-d** [comment]
Is it logistically easier to add you to this fork or for you to make a new
fork?  Does anything reference this repo in specific?

**Comment by marcan** [comment]
Nothing references this repo that I know of. If you don't mind me adding it to PyPI myself then it can point to mine; that would be easier for me and you wouldn't have to do anything, as long as you don't mind me effectively taking over and submitting it myself. I just want it to be in PyPI but I don't care if you add it and point it to your version, or if you would rather have me do it and point to my fork. If you do it yourself of course I hope you will take my contributions since I kind of need them :)

**Comment by andre-d** [comment]
Please go ahead and point whatever you need at your fork.  This was
basically just some test code and I was unaware anyone was actually using
it.

**Comment by marcan** [comment]
Thanks, will do. I'll of course make sure you're credited in the description page as the original author.

**Comment by ghost** [comment]
At the very least it's linked here: https://github.com/mpv-player/mpv/wiki/Scripting-language-bindings
